ALTER TABLE Student ADD CONSTRAINT NOT NULL birthday;

ALTER TABLE Mark ADD CONSTRAINT CHECK (mark >= 1 AND mark <= 10);
ALTER TABLE Mark ADD CONSTRAINT NOT NULL student_id;
ALTER TABLE Mark ADD CONSTRAINT NOT NULL subject_id;

ALTER TABLE Subject ADD CONSTRAINT CHECK (grade >= 1 AND grade <= 5);

ALTER TABLE paymenttype ADD CONSTRAINT NAME UNIQUE;

ALTER TABLE payment ADD CONSTRAINT NOT NULL type_id;
ALTER TABLE payment ADD CONSTRAINT NOT NULL amount;
ALTER TABLE payment ADD CONSTRAINT NOT NULL payment_date;
